### ISSUE TITLE
npy files required

### ISSUE THREAD

**Issue by yeanwei97** [dishank-b/MSCNN-Dehazing-Tensorflow#2]
May I know how can I get the npy files that you used for training?

**Comment by dishank-b** [comment]
I created the npy files using the dataset. You can use any dataset and generate npy using that.

**Comment by dishank-b** [comment]
Go through [utils.py](https://github.com/dishank-b/MSCNN-Dehazing-Tensorflow/blob/master/utils.py), this contains the code to generate npy. Make sure to comment/uncomment lines of code accordingly.

**Comment by yeanwei97** [comment]
Dear Mr Dishank Bansal,

I see, alright, I will try it. Thank you very much for guidance and reply.

Thank you
Lee Yean Wei
