### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by SchulerTsang** [dishank-b/MSCNN-Dehazing-Tensorflow#3]
Hi,I am using tensorflow 2.2.0 gpu with python 3.7.9 it does't work anyway guess due to the tensorflow version problem,any suggesion? I would be appreciate if you offer a piece of advice.

**Comment by dishank-b** [comment]
Yeah, it was for TensorFlow 1. If you wanna use TensorFlow 2, you will have to make the changes in the code itself. I can help you with any doubts you would have regarding any part of the code.
